/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Slava Z. (https://sketchfab.com/slava)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pony-cartoon-885d9f60b3a9429bb4077cfac5653cf9
title: Pony Cartoon
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("http://localhost:3000/model/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Body_SG1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Ground_SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Interior_SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Windows_SG} />
      </group>
    </group>
  );
}

useGLTF.preload("http://localhost:3000/model/scene.gltf");
